// Generated by gencpp from file object_tracking/ObstacleList.msg
// DO NOT EDIT!


#ifndef OBJECT_TRACKING_MESSAGE_OBSTACLELIST_H
#define OBJECT_TRACKING_MESSAGE_OBSTACLELIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <object_tracking/Obstacle.h>

namespace object_tracking
{
template <class ContainerAllocator>
struct ObstacleList_
{
  typedef ObstacleList_<ContainerAllocator> Type;

  ObstacleList_()
    : header()
    , cellLength(0.0)
    , cellWidth(0.0)
    , obstacles()  {
    }
  ObstacleList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cellLength(0.0)
    , cellWidth(0.0)
    , obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _cellLength_type;
  _cellLength_type cellLength;

   typedef double _cellWidth_type;
  _cellWidth_type cellWidth;

   typedef std::vector< ::object_tracking::Obstacle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::object_tracking::Obstacle_<ContainerAllocator> >::other >  _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::object_tracking::ObstacleList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_tracking::ObstacleList_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleList_

typedef ::object_tracking::ObstacleList_<std::allocator<void> > ObstacleList;

typedef boost::shared_ptr< ::object_tracking::ObstacleList > ObstacleListPtr;
typedef boost::shared_ptr< ::object_tracking::ObstacleList const> ObstacleListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_tracking::ObstacleList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_tracking::ObstacleList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_tracking::ObstacleList_<ContainerAllocator1> & lhs, const ::object_tracking::ObstacleList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cellLength == rhs.cellLength &&
    lhs.cellWidth == rhs.cellWidth &&
    lhs.obstacles == rhs.obstacles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_tracking::ObstacleList_<ContainerAllocator1> & lhs, const ::object_tracking::ObstacleList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::object_tracking::ObstacleList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_tracking::ObstacleList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_tracking::ObstacleList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_tracking::ObstacleList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_tracking::ObstacleList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_tracking::ObstacleList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_tracking::ObstacleList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af2b20df3d0fb51d9181cbe19cdcc2dc";
  }

  static const char* value(const ::object_tracking::ObstacleList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf2b20df3d0fb51dULL;
  static const uint64_t static_value2 = 0x9181cbe19cdcc2dcULL;
};

template<class ContainerAllocator>
struct DataType< ::object_tracking::ObstacleList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_tracking/ObstacleList";
  }

  static const char* value(const ::object_tracking::ObstacleList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_tracking::ObstacleList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 cellLength\n"
"float64 cellWidth\n"
"Obstacle[] obstacles\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: object_tracking/Obstacle\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 yaw\n"
"float64 pitch\n"
"float64 roll\n"
"int32 cluster\n"
"float64 speed\n"
;
  }

  static const char* value(const ::object_tracking::ObstacleList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_tracking::ObstacleList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cellLength);
      stream.next(m.cellWidth);
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_tracking::ObstacleList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_tracking::ObstacleList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cellLength: ";
    Printer<double>::stream(s, indent + "  ", v.cellLength);
    s << indent << "cellWidth: ";
    Printer<double>::stream(s, indent + "  ", v.cellWidth);
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::object_tracking::Obstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_TRACKING_MESSAGE_OBSTACLELIST_H
