// Generated by gencpp from file object_tracking/Obstacle.msg
// DO NOT EDIT!


#ifndef OBJECT_TRACKING_MESSAGE_OBSTACLE_H
#define OBJECT_TRACKING_MESSAGE_OBSTACLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_tracking
{
template <class ContainerAllocator>
struct Obstacle_
{
  typedef Obstacle_<ContainerAllocator> Type;

  Obstacle_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , pitch(0.0)
    , roll(0.0)
    , cluster(0)
    , speed(0.0)  {
    }
  Obstacle_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , pitch(0.0)
    , roll(0.0)
    , cluster(0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _roll_type;
  _roll_type roll;

   typedef int32_t _cluster_type;
  _cluster_type cluster;

   typedef double _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::object_tracking::Obstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_tracking::Obstacle_<ContainerAllocator> const> ConstPtr;

}; // struct Obstacle_

typedef ::object_tracking::Obstacle_<std::allocator<void> > Obstacle;

typedef boost::shared_ptr< ::object_tracking::Obstacle > ObstaclePtr;
typedef boost::shared_ptr< ::object_tracking::Obstacle const> ObstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_tracking::Obstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_tracking::Obstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_tracking::Obstacle_<ContainerAllocator1> & lhs, const ::object_tracking::Obstacle_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.yaw == rhs.yaw &&
    lhs.pitch == rhs.pitch &&
    lhs.roll == rhs.roll &&
    lhs.cluster == rhs.cluster &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_tracking::Obstacle_<ContainerAllocator1> & lhs, const ::object_tracking::Obstacle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::object_tracking::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_tracking::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_tracking::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_tracking::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_tracking::Obstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_tracking::Obstacle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_tracking::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43e8038953f6f9e758f835f0de07067c";
  }

  static const char* value(const ::object_tracking::Obstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43e8038953f6f9e7ULL;
  static const uint64_t static_value2 = 0x58f835f0de07067cULL;
};

template<class ContainerAllocator>
struct DataType< ::object_tracking::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_tracking/Obstacle";
  }

  static const char* value(const ::object_tracking::Obstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_tracking::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 yaw\n"
"float64 pitch\n"
"float64 roll\n"
"int32 cluster\n"
"float64 speed\n"
;
  }

  static const char* value(const ::object_tracking::Obstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_tracking::Obstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.cluster);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_tracking::Obstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_tracking::Obstacle_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "cluster: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cluster);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_TRACKING_MESSAGE_OBSTACLE_H
